---
title: "vignettes-distanceMonitorafloresta"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{distanceMonitorafloresta}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Indice

O pacote distanxceMonitoraflorestal foi desenvolvido para atender uma demanda do ICMBio que necessita aplicar a base de dados do [Programa Monitora CENAP/CEMAVE](https://www.gov.br/icmbio/pt-br/assuntos/monitoramento) para obter estimativas de densidade populacional de aves e médios e grandes mamíferos de 40 Unidades de Conservação do Brasil. O objetivo do pacote é facilitar a exploração e análise dos dados oferencendo ao usuário funções intuitivas, com nome e documentação em português. As funções cobrem tarefas de todas as etapas de um fluxo de análise de dados para obtenção de estimativas de densidade populacional a partir de dados obtidos por amostragem por distância: transformação, seleção de variáveis, visualização e análise dos dados, estas com saídas em formatos gráfico e de tabelas para serem utilizados em relatórios para a apresntação dos resultados. Exemplos de como utilizar o pacote são fornecidos nos vignettes:

- [Carregando-uma-base-de-dados-atualizada](Carregando-uma-base-de-dados-atualizada.html);

- [Checagem-filtragem-e-transformacao-dos-dados](Checagem-filtragem-e-transformacao-dos-dados.html);

- [Ajuste-dos-modelos-dist-exatas-com-repeticao](Ajuste-dos-modelos-dist-exatas-com-repeticao.html);

- [Ajuste-dos-modelos-dist-exatas-sem-repeticao](Ajuste-dos-modelos-dist-exatas-sem-repeticao.html);

- [Ajuste-dos-modelos-dist-agrup-com-repeticoes](Ajuste-dos-modelos-dist-agrup-com-repeticoes.html)

- [Ajuste-dos-modelos-multiplas-covariaveis](Ajuste-dos-modelos-multiplas-covariaveis.html);

- [Ajuste-dos-modelos-dist-estratificada-por-uc](Ajuste-dos-modelos-dist-estratificada-por-uc.html);

- [Ajuste-dos-modelos-dist-estratificada-por-ano](Ajuste-dos-modelos-dist-estratificada-por-ano.html)
