---
title: "distanceMonitoraflorestal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{distanceMonitoraflorestal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

O pacote distanxceMonitoraflorestal foi desenvolvido para atender uma demanda do ICMBio que necessita aplicar a base de dados do [Programa Monitora CENAP/CEMAVE](https://www.gov.br/icmbio/pt-br/assuntos/monitoramento) para obter estimativas de densidade populacional de aves e médios e grandes mamíferos de 40 Unidades de Conservação do Brasil. O objetivo do pacote é facilitar a exploração e análise dos dados oferencendo ao usuário funções intuitivas, com nome e [documentação](https://vntborgesjr.github.io/distanceMonitoraflorestal/index.html) em português. As funções cobrem tarefas de todas as etapas de um fluxo de análise de dados para obtenção de estimativas de densidade populacional a partir de dados obtidos por amostragem por distância: transformação, seleção de variáveis, visualização e análise dos dados, estas com saídas em formatos gráfico e de tabelas para serem utilizados em relatórios para a apresntação dos resultados. Exemplos de como utilizar o pacote são fornecidos nos vignettes:

- [Carregando uma base de dados atualizada](Carregando-uma-base-de-dados-atualizada.html);

- [Checagem filtragem e transformação dos dados](Checagem-filtragem-e-transformacao-dos-dados.html);

- [Exploração e seleção dos dados para as análises](Exploracao-e-selecao-de-dados-para-analises.html);

- [Ajuste dos modelos com amostras repetidas](Fluxo1-distancias-exatas-com-repeticoes.html);

- [Ajuste dos modelos sem amostras repetidas](Fluxo2-distancias-exatas-sem-repeticoes.html);

- [Ajuste dos modelos com amostras repetidas e distâncias agrupadas](Fluxo3-distancias-agrupadas-com-repeticoes.html)

- [Ajuste dos modelos com multiplas covariaveis](Fluxo4-multiplas-covariaveis.html);

- [Ajuste dos modelos com estratificação por Unidade de Conservação](Fluxo5-estratificacao-por-unidade-de-conservacao.html);

- [Ajuste dos modelos com estratificação por ano](Fluxo6-estratificacao-por-ano.html)
